[package]
name = "basic_problems"
version = "0.0.1"
authors = ["Duong Do Minh Chau <duongdominhchau@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
